### ISSUE TITLE
`dist` folder is not included in 0.3.1

### ISSUE THREAD

**Issue by Vinnl** [JSBros/react-tinyletter#7]
I'm not quite sure how it happened, but I get the following error after upgrading to 0.3.1:

> Module not found: Error: Can't resolve 'react-tinyletter'

After digging into `node_modules/react-tinyletter`, it turns out that there's no `dist` folder, so I guess something went wrong when publishing that version?

**Comment by ariamckinley** [comment]
hrm that's odd, I deploy using `np` so that should auto-build, I'll push out another release.

**Comment by ariamckinley** [comment]
I pushed `0.3.2`, let me know if this resolves it for you!

**Comment by Vinnl** [comment]
That was fast! And yes, it does, thanks :)
